# Generated by Django 6.0.6 on 2026-06-30 02:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('satellite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='WGS84 lon/lat of the station', srid=4326)),
                ('community', models.CharField(blank=True, db_index=True, help_text="Local community / neighbourhood name, e.g. 'Alajo', 'Agbogbloshie'", max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Under Maintenance'), ('faulty', 'Faulty')], db_index=True, default='offline', max_length=20)),
                ('installed_date', models.DateTimeField(auto_now_add=True)),
                ('last_reading_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('battery_level', models.FloatField(default=100.0, help_text='Percent, 0-100')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('serial_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('flood_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='satellite.floodzone')),
            ],
            options={
                'verbose_name': 'Sensor Station',
                'verbose_name_plural': 'Sensor Stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('water_level_cm', models.FloatField(help_text='Water level above the gauge datum, in cm')),
                ('rainfall_mm', models.FloatField(help_text='Rainfall accumulated since last reading, in mm')),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('battery_voltage', models.FloatField(blank=True, null=True)),
                ('signal_strength', models.IntegerField(blank=True, help_text='RSSI, dBm', null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Set True once the reading has passed range/rate-of-change validation')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensorstation')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='sensorstation',
            index=models.Index(fields=['status', 'last_reading_at'], name='sensors_sen_status_1a87a7_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['station', '-timestamp'], name='sensors_sen_station_dbaf80_idx'),
        ),
    ]
