# Generated by Django 6.0.6 on 2026-06-30 02:00

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('satellite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('severity', models.CharField(choices=[('green', 'Safe'), ('yellow', 'Watch'), ('orange', 'Warning'), ('red', 'Emergency')], db_index=True, max_length=10)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('dashboard', 'Dashboard Only')], db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('suppressed', 'Suppressed (Cooldown)')], db_index=True, default='pending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, help_text='Twilio message SID, for delivery-status webhook matching', max_length=100)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('severity', models.CharField(choices=[('minor', 'Minor — ankle deep'), ('moderate', 'Moderate — knee deep'), ('severe', 'Severe — waist deep or higher')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='community_reports/%Y/%m/')),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Community Report',
                'verbose_name_plural': 'Community Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FloodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('severity', models.CharField(choices=[('green', 'Safe'), ('yellow', 'Watch'), ('orange', 'Warning'), ('red', 'Emergency')], db_index=True, max_length=10)),
                ('triggered_by', models.CharField(choices=[('sensor', 'IoT Sensor'), ('satellite', 'Satellite'), ('combined', 'IoT + Satellite'), ('community', 'Community Report'), ('manual', 'Manual (Admin)')], db_index=True, max_length=20)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('affected_area_ha', models.FloatField(default=0.0)),
                ('affected_area_geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('peak_water_level_cm', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Flood Event',
                'verbose_name_plural': 'Flood Events',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFloodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event_date', models.DateField(db_index=True)),
                ('severity', models.CharField(choices=[('green', 'Safe'), ('yellow', 'Watch'), ('orange', 'Warning'), ('red', 'Emergency')], max_length=10)),
                ('rainfall_mm', models.FloatField(blank=True, null=True)),
                ('affected_area_ha', models.FloatField(blank=True, null=True)),
                ('casualties', models.PositiveIntegerField(default=0)),
                ('displaced_persons', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(blank=True, help_text="e.g. 'NADMO report 2023', 'GhanaWeb article'", max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Historical Flood Record',
                'verbose_name_plural': 'Historical Flood Records',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(db_index=True, help_text='E.164 format', max_length=20)),
                ('preferred_channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('dashboard', 'Dashboard Only')], default='whatsapp', max_length=20)),
                ('min_severity', models.CharField(choices=[('green', 'Safe'), ('yellow', 'Watch'), ('orange', 'Warning'), ('red', 'Emergency')], default='orange', help_text='Only notify at or above this severity', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('flood_zones', models.ManyToManyField(blank=True, help_text='Zones this recipient wants alerts for. Empty = all zones.', related_name='subscribers', to='satellite.floodzone')),
            ],
            options={
                'verbose_name': 'Alert Recipient',
                'verbose_name_plural': 'Alert Recipients',
                'ordering': ['full_name'],
            },
        ),
    ]
