# Generated by Django 6.0.6 on 2026-06-30 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('satellite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrecipient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.alertrecipient'),
        ),
        migrations.AddField(
            model_name='communityreport',
            name='flood_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_reports', to='satellite.floodzone'),
        ),
        migrations.AddField(
            model_name='communityreport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityreport',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='flood_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flood_events', to='satellite.floodzone'),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='related_flood_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flood_events', to='satellite.floodmap'),
        ),
        migrations.AddField(
            model_name='communityreport',
            name='related_flood_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_reports', to='alerts.floodevent'),
        ),
        migrations.AddField(
            model_name='alert',
            name='flood_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.floodevent'),
        ),
        migrations.AddField(
            model_name='historicalfloodrecord',
            name='flood_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_records', to='satellite.floodzone'),
        ),
        migrations.AddIndex(
            model_name='floodevent',
            index=models.Index(fields=['flood_zone', '-started_at'], name='alerts_floo_flood_z_cbada3_idx'),
        ),
        migrations.AddIndex(
            model_name='communityreport',
            index=models.Index(fields=['is_verified', '-created_at'], name='alerts_comm_is_veri_1fd161_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['recipient', '-created_at'], name='alerts_aler_recipie_a8ffa0_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['flood_event', 'channel'], name='alerts_aler_flood_e_0253ce_idx'),
        ),
    ]
