# Generated by Django 6.0.6 on 2026-06-30 02:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloodZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=150)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('description', models.TextField(blank=True)),
                ('current_risk_level', models.CharField(choices=[('green', 'Safe'), ('yellow', 'Watch'), ('orange', 'Warning'), ('red', 'Emergency')], db_index=True, default='green', max_length=10)),
                ('water_level_threshold_cm', models.FloatField(default=50.0, help_text='Water level above which this zone is considered at risk')),
                ('rainfall_threshold_mm', models.FloatField(default=40.0, help_text='Rainfall (mm/hour) above which this zone is considered at risk')),
                ('population_estimate', models.PositiveIntegerField(blank=True, null=True)),
                ('last_assessed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Flood Risk Zone',
                'verbose_name_plural': 'Flood Risk Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SatelliteScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('scene_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('source', models.CharField(choices=[('sentinel-1', 'Sentinel-1 (SAR)'), ('sentinel-2', 'Sentinel-2 (Optical)'), ('landsat', 'Landsat')], db_index=True, max_length=20)),
                ('provider', models.CharField(help_text='e.g. planetary_computer, copernicus', max_length=50)),
                ('acquisition_date', models.DateTimeField(db_index=True)),
                ('cloud_cover_pct', models.FloatField(blank=True, null=True)),
                ('footprint', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='discovered', max_length=20)),
                ('raw_path', models.CharField(blank=True, help_text='Local/S3 path to raw download', max_length=500)),
                ('preprocessed_path', models.CharField(blank=True, help_text='Path to prepare_for_ai() output', max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Raw STAC properties')),
            ],
            options={
                'verbose_name': 'Satellite Scene',
                'verbose_name_plural': 'Satellite Scenes',
                'ordering': ['-acquisition_date'],
                'indexes': [models.Index(fields=['source', 'status', '-acquisition_date'], name='satellite_s_source_b90851_idx')],
            },
        ),
        migrations.CreateModel(
            name='FloodMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('extent_geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Vectorised flood extent', null=True, srid=4326)),
                ('raster_path', models.CharField(blank=True, help_text='Path to flood mask GeoTIFF', max_length=500)),
                ('flooded_area_ha', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0, help_text='0-1, derived from MNDWI threshold strength / IoT confirmation')),
                ('confirmed_by_sensors', models.BooleanField(default=False, help_text='True when sensor readings in this zone corroborate the satellite detection')),
                ('detection_method', models.CharField(default='mndwi_threshold', help_text='e.g. mndwi_threshold, changeformer, sar_backscatter', max_length=50)),
                ('statistics', models.JSONField(blank=True, default=dict)),
                ('flood_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flood_maps', to='satellite.floodzone')),
                ('source_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flood_maps', to='satellite.satellitescene')),
            ],
            options={
                'verbose_name': 'Flood Map',
                'verbose_name_plural': 'Flood Maps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['flood_zone', '-created_at'], name='satellite_f_flood_z_55b16d_idx')],
            },
        ),
    ]
